# Use zsh
set-option -g default-shell /bin/zsh

# Prefix
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Reload Config
bind r source-file ~/.tmux.conf

# Base Index
set -g base-index 1
set -g detach-on-destroy off

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind '%'
unbind 'C-w'

# Mouse mode
set -g mouse on

# Enable Vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Don't rename windows
set-option -g allow-rename off
set -g renumber-windows on

# History
set -g history-limit 100000

# Command to change default directory  
bind -n M-c new-window -c '#{pane_current_path}'
bind -n M-| split-window -h -c '#{pane_current_path}'
bind -n M-- split-window -v -c '#{pane_current_path}'
bind -n C-M-h previous-window
bind -n C-M-j switch-client -p
bind -n C-M-k switch-client -n
bind -n C-M-l next-window

# Allow images
set -gq allow-passthrough on
set -g visual-activity off

# Visual stuff
set -g status-position top
set -g status-style 'fg=#d65d0e,bg=color0'

set -g window-status-current-format '#[fg=color0,bg=#d65d0e]( #I #W )'
set -g window-status-format '#[fg=#d65d0e,bg=color0,default][ #I #W ]'
set -g window-status-separator ' 󱓸 '
set -g status-left ' [#{session_name}] 󱓸  '

set -g status-right '#{pomodoro_status} 󱓸 %H:%M:%S 󱓸 #{ip} 󱓸 #{battery_icon_charge} #{battery_percentage} '
set -g status-interval 1

set -g status-left-length 100
set -g status-right-length 100

set-option -ga terminal-overrides ",xterm-256color:Tc"

# Battery config
set -g @batt_icon_charge_tier8 '🌕'
set -g @batt_icon_charge_tier7 '🌖'
set -g @batt_icon_charge_tier6 '🌖'
set -g @batt_icon_charge_tier5 '🌗'
set -g @batt_icon_charge_tier4 '🌗'
set -g @batt_icon_charge_tier3 '🌘'
set -g @batt_icon_charge_tier2 '🌘'
set -g @batt_icon_charge_tier1 '🌑'

# Pomodoro config
set -g @pomodoro_notifications 'on'
set -g @pomodoro_granularity 'on'
set -g @pomodoro_on '🤫 '
set -g @pomodoro_complete '🥳 '
set -g @pomodoro_pause '🫢 '

# Source Neovim Navigation File
source-file ~/.config/tmux/nvim-navigator.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'TamDik/ip.tmux'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

run '~/.tmux/plugins/tpm/tpm'


